This function returns true if an exception has been thrown but not yet caught. Once
caught, the function returns false.
    bool uncaught_exception( );